=== jgrall/Xen-unstable/tools/misc/policyprocessor/SecurityPolicySpec.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Author: Ray Valdez, rvaldez@us.ibm.com -->
<!-- xml schema definition for xen xml policies -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.ibm.com"
xmlns="http://www.ibm.com" 
elementFormDefault="qualified">

<xsd:element name="TE" type="xsd:string" />
<xsd:element name="ChWall" type="xsd:string" />

<xsd:element name="Definition">
  <xsd:complexType>
 	<xsd:sequence>

	  <!-- simple type enforcement -->
	  <xsd:element name="Types" minOccurs ="0" maxOccurs="1">
		<xsd:complexType>
		  <xsd:sequence>
			<xsd:element ref="TE" minOccurs ="1" maxOccurs ="unbounded"/>
		  </xsd:sequence>
		</xsd:complexType>
	  </xsd:element>

	  <!-- chinese wall -->
	  <!--   type definition -->
	  <xsd:element name="ChWallTypes" minOccurs ="0" maxOccurs="1">
		<xsd:complexType>
		  <xsd:sequence>
			<xsd:element ref="ChWall"  minOccurs ="1" maxOccurs ="unbounded"/>

      	   	</xsd:sequence>
          </xsd:complexType>
	</xsd:element>

  	<!--   conflict set -->
	  <xsd:element name="ConflictSet" minOccurs ="0" maxOccurs="unbounded">
		<xsd:complexType>
		  <xsd:sequence>
			<xsd:element ref="ChWall"  minOccurs ="2" maxOccurs ="unbounded"/>
		  </xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	</xsd:sequence>
  </xsd:complexType>
</xsd:element>

<xsd:element name="Policy">
    <xsd:complexType>
      <xsd:sequence>

	<xsd:element name="PolicyHeader">
    	<xsd:complexType>
      	   <xsd:all>
		<xsd:element name = "Name" type="xsd:string"/>
		<xsd:element name = "DateTime" type="xsd:dateTime"/>
		<xsd:element name = "Tag" minOccurs ="1" maxOccurs ="1" type="xsd:string"/>
		<xsd:element name = "TypeDefinition">
    		<xsd:complexType>
      	   	  <xsd:all>
			<xsd:element name = "url" type="xsd:string"/>
			<xsd:element name = "hash" minOccurs ="0" maxOccurs ="1" type="xsd:string"/>
      	   	  </xsd:all>
    		</xsd:complexType>
		</xsd:element>

      	   </xsd:all>
    	</xsd:complexType>
	</xsd:element>

	<xsd:element name="VM" minOccurs ="1" maxOccurs="unbounded">
    	  <xsd:complexType>
      	   <xsd:sequence>
		<xsd:element name="id" type="xsd:integer"/>
		<xsd:element ref="TE" minOccurs="0" maxOccurs="unbounded" />
		<xsd:element ref="ChWall" minOccurs ="0" maxOccurs="unbounded"/>
      	   </xsd:sequence>
    	  </xsd:complexType>
	</xsd:element>

	<xsd:element name="Vlan" minOccurs ="0" maxOccurs="unbounded">
    	  <xsd:complexType>
      	   <xsd:sequence>
		<xsd:element name="vid" type="xsd:integer"/>
		<xsd:element ref="TE" minOccurs="1" maxOccurs="unbounded" />
      	   </xsd:sequence>
    	  </xsd:complexType>
	</xsd:element>

	<xsd:element name="Slot" minOccurs ="0" maxOccurs="unbounded">
    	  <xsd:complexType>
      	   <xsd:sequence>
		<xsd:element name="bus" type="xsd:integer"/>
		<xsd:element name="slot" type="xsd:integer"/>
		<xsd:element ref="TE" minOccurs="1" maxOccurs="unbounded" />
      	   </xsd:sequence>
    	  </xsd:complexType>
	</xsd:element>


      </xsd:sequence>
    </xsd:complexType>
</xsd:element>

<!-- root element -->
<xsd:element name="SecurityPolicySpec">
    <xsd:complexType>
      <xsd:choice>
		<xsd:element ref="Definition" minOccurs ="1" maxOccurs="unbounded"/>
		<xsd:element ref="Policy" minOccurs ="1" maxOccurs="unbounded"/>
      </xsd:choice>
    </xsd:complexType>
</xsd:element>
</xsd:schema>

=== jgrall/Xen-unstable/tools/misc/policyprocessor/xen_sample_policy.xml
<?xml version="1.0"?>
<!-- Author: Ray Valdez, rvaldez@us.ibm.com -->
<!-- example xen policy file -->

<SecurityPolicySpec
xmlns="http://www.ibm.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.ibm.com SecurityPolicySpec.xsd">
<Policy>
 <PolicyHeader>
        <Name>xen sample policy</Name>
        <DateTime>2005-05-20T16:56:00</DateTime>
        <Tag>foobar</Tag>
        <TypeDefinition>
          <url>xen_sample_def.xml</url>
          <hash>abcdef123456abcdef</hash>
        </TypeDefinition>
 </PolicyHeader>

 <VM>
        <id> 0 </id>
        <TE>LOCAL-management</TE>
        <TE>R-Company-development</TE>
        <TE>S-Company-order</TE>
        <TE>T-Company-advertising</TE>
        <TE>U-Company-computing</TE>
		 <ChWall>Q-Company</ChWall>
 </VM>

 <VM>
        <id> 1 </id>
        <TE>R-Company-development</TE>
		 <ChWall>R-Company</ChWall>
 </VM>

 <VM>
        <id> 2 </id>
        <TE>S-Company-order</TE>
		 <ChWall>S-Company</ChWall>

 </VM>

 <VM>
        <id> 3 </id>
        <TE>T-Company-advertising</TE>
		 <ChWall>T-Company</ChWall>
 </VM>


 <VM>
        <id> 4 </id>
        <TE>U-Company-computing</TE>
		 <ChWall>U-Company</ChWall>
 </VM>


</Policy>
</SecurityPolicySpec>

=== jgrall/Xen-unstable/tools/misc/policyprocessor/xen_sample_def.xml
<?xml version="1.0"?>
<!-- Author: Ray Valdez, rvaldez@us.ibm.com -->
<!-- example policy type definition -->
<SecurityPolicySpec
xmlns="http://www.ibm.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.ibm.com SecurityPolicySpec.xsd">

<Definition>
<!-- an example of a simple type enforcement type definition -->
  <Types>
        <TE>LOCAL-management</TE>
        <TE>R-Company-development</TE>
        <TE>S-Company-order</TE>
        <TE>T-Company-advertising</TE>
        <TE>U-Company-computing</TE>
		 <!-- TE nondevelopment  -->
  </Types>

<!-- an example of a chinese wall type definition along with conflict sets-->
  <ChWallTypes>
		 <ChWall>Q-Company</ChWall>
		 <ChWall>R-Company</ChWall>
		 <ChWall>S-Company</ChWall>
		 <ChWall>T-Company</ChWall>
		 <ChWall>U-Company</ChWall>
		 <ChWall>V-Company</ChWall>
		 <ChWall>W-Company</ChWall>
		 <ChWall>X-Company</ChWall>
		 <ChWall>Y-Company</ChWall>
		 <ChWall>Z-Company</ChWall>
  </ChWallTypes>

  <ConflictSet>
		 <ChWall>T-Company</ChWall>
		 <ChWall>S-Company</ChWall>
   </ConflictSet>

   <ConflictSet>
		 <ChWall>R-Company</ChWall>
		 <ChWall>V-Company</ChWall>
		 <ChWall>W-Company</ChWall>
   </ConflictSet>

</Definition>
</SecurityPolicySpec>
